In [ ]:
Theoretical questions : 

In [ ]:
# 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it  enhance Python's capabilities for numerical operations?

NumPy, which stands for Numerical Python, is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. Here’s an overview of its purpose and advantages:

Purpose of NumPy:
1. Efficient Array Operations: NumPy introduces the ndarray object, a fast, flexible container for large datasets in Python. This object allows you to perform mathematical operations on arrays efficiently.
2. Numerical Computation: It offers a vast array of mathematical functions for performing operations on arrays, including statistical operations, linear algebra operations, and Fourier transforms.
3. Integration: NumPy serves as the foundation for many other scientific computing libraries in Python, such as SciPy, pandas, and scikit-learn.

Advantages of NumPy:
1. Performance: NumPy arrays are more efficient than Python’s built-in lists, especially for large datasets. They are implemented in C and optimized for performance, allowing for faster execution of operations.
2. Vectorization: NumPy supports vectorized operations, which means you can perform element-wise operations on entire arrays without needing explicit loops. This results in more concise and readable code and can lead to performance improvements.
3. Broadcasting: This feature allows NumPy to perform operations on arrays of different shapes in a way that is compatible with the operation, avoiding the need for manual expansion of arrays.
4. Convenience: NumPy provides a range of functions for common mathematical operations, random number generation, and array manipulation, which simplifies coding and reduces the likelihood of errors.
5. Interoperability: NumPy arrays can easily be integrated with other libraries, making it a crucial part of the scientific Python ecosystem. For instance, pandas uses NumPy under the hood for handling numerical data.
6. Memory Efficiency: NumPy arrays consume less memory compared to Python lists, as they store data in contiguous blocks of memory, reducing overhead.

Enhancing Python's Numerical Capabilities:
1. Efficiency and Speed: By using compiled C code, NumPy operations are significantly faster than Python’s native list operations.
2. Array Operations: NumPy allows for operations on multi-dimensional arrays, which would be cumbersome and less efficient using native Python lists.
3. Mathematical Functions: It provides a wide range of mathematical functions optimized for performance and accuracy.
4. Integration: NumPy's arrays and operations serve as the backbone for many advanced libraries in scientific computing and data analysis.

In [ ]:
# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

np.mean()

- Purpose: Calculates the arithmetic mean of the array elements.
- Syntax: np.mean(a, axis=None, dtype=None, out=None, keepdims=False)
- Parameters:
1. a: Input array.
2. axis: Axis or axes along which the means are computed. Default is None, which computes the mean of the flattened array.
3. dtype: Data type used in computation.
4. out: A location into which the result is stored.
5. keepdims: If True, the axes which are reduced are left in the result as dimensions with size one.
6. Usage: Use np.mean() when you want to compute the average value of the elements in an array.

Example:
import numpy as np
data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)



np.average()

- Purpose: Computes the weighted average of array elements. It can also compute the mean if no weights are provided.
- Syntax: np.average(a, axis=None, weights=None, returned=False)
- Parameters:
1. a: Input array.
2. axis: Axis or axes along which the averages are computed. Default is None.
3. weights: Array of weights associated with the elements. If not provided, the simple mean is computed.
4. returned: If True, a tuple is returned where the first element is the average and the second is the sum of weights.
5. Usage: Use np.average() when you need to compute a weighted average or need more control over the averaging process.

Example:
import numpy as np
data = np.array([1, 2, 3, 4, 5])
weights = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
weighted_average = np.average(data, weights=weights)

In [ ]:
# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.


Reversing NumPy arrays along different axes can be efficiently done using slicing. Here’s a detailed look at how you can reverse arrays for both 1D and 2D cases:

1D Array Reversal
For a 1D array, you can reverse the entire array using slicing.

Example:

import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_array_1d = array_1d[::-1]

print("Original 1D array:", array_1d)
print("Reversed 1D array:", reversed_array_1d)
#output: Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


2D Array Reversal
For a 2D array, you can reverse the array along specific axes or both axes:

1. Reverse Along Rows (axis=0): This reverses the order of the rows while keeping the columns in the same order.

Example : 
    import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse along rows (axis=0)
reversed_rows = array_2d[::-1, :]

print("Original 2D array:\n", array_2d)
print("Reversed along rows:\n", reversed_rows)
#output: Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]

2. Reverse Along Columns (axis=1): This reverses the order of the columns while keeping the rows in the same order.

Example:

import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse along columns (axis=1)
reversed_columns = array_2d[:, ::-1]

print("Original 2D array:\n", array_2d)
print("Reversed along columns:\n", reversed_columns)
# Output:
Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along columns:
[[3 2 1]
 [6 5 4]
 [9 8 7]]

3. Reverse Both Rows and Columns: To reverse the array along both rows and columns, you can combine the two slicing operations.

Example:

import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse both rows and columns
reversed_both = array_2d[::-1, ::-1]

print("Original 2D array:\n", array_2d)
print("Reversed both rows and columns:\n", reversed_both)
# Output:
Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed both rows and columns:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

In [ ]:
# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Determining the Data Type
Example:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Determine the data type of the array elements
data_type = array.dtype

print("Data type of the array elements:", data_type)
# Output:
Data type of the array elements: int64
In this example, array.dtype returns int64, which indicates that the elements of the array are 64-bit integers.


Importance of Data Types in Memory Management and Performance
1. Memory Efficiency: Different data types require different amounts of memory. For example, an int8 (8-bit integer) requires less memory than an int64 (64-bit integer). By choosing the appropriate data type, you can minimize memory usage.
This is particularly important when working with large datasets or arrays, as using a more compact data type can significantly reduce the memory footprint.

2. Performance: Operations on arrays with smaller data types can be faster because they involve less data to process. For example, arithmetic operations on float32 arrays can be faster than on float64 arrays due to the smaller size of each element.
NumPy's performance is optimized for specific data types. Using a data type that matches the needs of your application can enhance performance by aligning with hardware and NumPy’s internal optimizations.

3.Precision and Range: Different data types offer different ranges and precision. For example, float32 has less precision and a smaller range compared to float64. Choosing the correct data type helps ensure that your computations are accurate and that they fit within the range of the data type.
Using a data type with insufficient precision can lead to rounding errors or overflow issues.

4. Compatibility: NumPy operations and functions expect inputs of specific data types. Ensuring that your arrays use the correct data type helps avoid type-related errors and ensures compatibility with NumPy’s functions and methods.

5. Data Type Conversion: You can change the data type of an array using the astype() method if needed. For example, array.astype(np.float32) converts an array to a float32 data type. This can be useful for optimizing memory usage or compatibility with other systems or libraries.


Example:
import numpy as np

# Create an integer array
int_array = np.array([1, 2, 3, 4, 5])

# Convert to float32
float_array = int_array.astype(np.float32)

print("Original data type:", int_array.dtype)
print("Converted data type:", float_array.dtype)
# Output:
Original data type: int64
Converted data type: float32

In [ ]:
# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In NumPy, ndarray (short for "n-dimensional array") is a core data structure that represents a multidimensional, homogeneous array of fixed-size items. Here’s an overview of ndarray and how it differs from standard Python lists:

Key Features of ndarray:
1. Homogeneity:
ndarray: All elements in a NumPy array are of the same data type. This uniformity allows for more efficient storage and computation.
Python List: Can contain elements of different data types (e.g., integers, floats, strings) within the same list.

2. Multidimensional:
ndarray: Supports multiple dimensions (e.g., 1D, 2D, 3D). You can create arrays with any number of dimensions.
Python List: Primarily 1-dimensional. Nested lists can simulate multidimensional arrays, but this is less efficient and more cumbersome to work with.

3. Efficient Memory Usage:
ndarray: Optimized for performance and memory usage. Data is stored in contiguous blocks of memory, which reduces overhead and improves speed.
Python List: Less memory-efficient due to the overhead of storing various data types and dynamic resizing.

4. Vectorized Operations:
ndarray: Supports vectorized operations, allowing element-wise operations on arrays without explicit loops. This leads to more concise and faster code.
Python List: Operations are not vectorized. You need to use explicit loops or list comprehensions for element-wise operations.

5. Broadcasting:
ndarray: Supports broadcasting, which allows operations on arrays of different shapes in a compatible manner. This simplifies code and reduces the need for manual array expansion.
Python List: Does not support broadcasting. Operations require manual handling of array shapes and expansion.

6. Mathematical and Statistical Functions:
ndarray: Comes with a comprehensive set of mathematical, statistical, and linear algebra functions optimized for performance.
Python List: Requires external libraries or custom code for mathematical operations, making it less convenient for numerical computations.

7. Shape and Reshaping:
ndarray: Arrays have a fixed shape, but you can reshape them without changing the data. This flexibility is useful for various data processing tasks.
Python List: Lists do not have a concept of shape. Reshaping requires manual reconstruction of the list structure.


Example Comparison:
    
    
1. Creating and Using a 1D Array in NumPy:

import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Perform element-wise operation
squared_array = array ** 2

print("Original array:", array)
print("Squared array:", squared_array)


2. Creating and Using a 1D List in Python:

# Create a Python list
list_data = [1, 2, 3, 4, 5]

# Perform element-wise operation using a list comprehension
squared_list = [x ** 2 for x in list_data]

print("Original list:", list_data)
print("Squared list:", squared_list)


# Output:

Original array: [1 2 3 4 5]
Squared array: [ 1  4  9 16 25]


Original list: [1, 2, 3, 4, 5]
Squared list: [1, 4, 9, 16, 25]

In [ ]:
# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

1. Efficient Memory Management
Contiguous Memory Allocation: NumPy arrays store data in contiguous blocks of memory, which allows for efficient access and manipulation. This reduces overhead and improves cache performance.
Fixed Data Types: All elements in a NumPy array have the same data type, which allows for efficient use of memory and data processing. Python lists, on the other hand, store references to objects and can have elements of different types, leading to additional memory overhead.

Example:
import numpy as np
import sys

# Python list
py_list = [1, 2, 3, 4, 5]
list_size = sys.getsizeof(py_list)

# NumPy array
np_array = np.array([1, 2, 3, 4, 5])
array_size = np_array.nbytes

print("Size of Python list:", list_size)
print("Size of NumPy array:", array_size)


2. Performance of Mathematical Operations
Vectorization: NumPy uses vectorized operations, meaning operations are applied to entire arrays at once rather than element by element. This is achieved through highly optimized C and Fortran code, which can leverage SIMD (Single Instruction, Multiple Data) instructions.
Python Lists: Operations on Python lists are not vectorized, so you need to use explicit loops or list comprehensions, which are less efficient.

Example:
import numpy as np
import time

# Large scale operation with NumPy
np_array = np.arange(1e6)
start_time = time.time()
result_np = np_array ** 2
end_time = time.time()
print("NumPy operation time:", end_time - start_time)

# Large scale operation with Python lists
py_list = list(range(int(1e6)))
start_time = time.time()
result_py = [x ** 2 for x in py_list]
end_time = time.time()


print("Python list operation time:", end_time - start_time)
3. Broadcasting and Reshaping
Broadcasting: NumPy supports broadcasting, allowing operations on arrays of different shapes without the need for explicit looping or manual expansion. This can greatly simplify code and improve performance.
Python Lists: Do not support broadcasting. You would need to manually handle operations involving different shapes or dimensions, which can be cumbersome and less efficient.

Example:
import numpy as np

# Broadcasting with NumPy
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([1, 0, -1])
result = array1 + array2

print("Broadcasted result:\n", result)


4. Optimized Algorithms
Specialized Libraries: NumPy integrates with highly optimized linear algebra libraries like BLAS and LAPACK. These libraries are written in low-level languages and are optimized for performance on various hardware architectures.
Python Lists: No such optimizations are available, so large-scale numerical computations are less efficient when using Python lists.

Example:
import numpy as np

# Large matrix multiplication with NumPy
matrix1 = np.random.rand(1000, 1000)
matrix2 = np.random.rand(1000, 1000)
start_time = time.time()
result = np.dot(matrix1, matrix2)
end_time = time.time()
print("Matrix multiplication time:", end_time - start_time)

In [ ]:
# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

numpy.vstack()

Purpose: Stacks arrays vertically (row-wise), meaning it combines arrays along the first axis (axis 0). The arrays need to have the same number of columns.
Syntax: numpy.vstack(tup)
tup: A sequence of arrays to be stacked. All arrays must have the same number of columns.

Example:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Stack arrays vertically
stacked_v = np.vstack((array1, array2))

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Stacked Vertically:\n", stacked_v)

#Output:
Array 1:
 [[1 2 3]
  [4 5 6]]
Array 2:
 [[ 7  8  9]
  [10 11 12]]
Stacked Vertically:
 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]


numpy.hstack()
Purpose: Stacks arrays horizontally (column-wise), meaning it combines arrays along the second axis (axis 1). The arrays need to have the same number of rows.
Syntax: numpy.hstack(tup)
tup: A sequence of arrays to be stacked. All arrays must have the same number of rows.

Example:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Stack arrays horizontally
stacked_h = np.hstack((array1, array2))

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Stacked Horizontally:\n", stacked_h)

#Output:
Array 1:
 [[1 2 3]
  [4 5 6]]
Array 2:
 [[ 7  8  9]
  [10 11 12]]
Stacked Horizontally:
 [[ 1  2  3  7  8  9]
  [ 4  5  6 10 11 12]]

In [ ]:
# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

numpy.fliplr()
Purpose: Flips an array horizontally (left to right).
Effect: Reverses the order of elements along the horizontal axis (axis 1), which means it mirrors the array along its vertical axis.
Applicable to: 2D arrays (matrices).

Example:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Flip array horizontally
flipped_lr = np.fliplr(array_2d)

print("Original 2D array:\n", array_2d)
print("Horizontally flipped array:\n", flipped_lr)

#Output:
Original 2D array:
 [[1 2 3]
  [4 5 6]
  [7 8 9]]
Horizontally flipped array:
 [[3 2 1]
  [6 5 4]
  [9 8 7]]


numpy.flipud()
Purpose: Flips an array vertically (up to down).
Effect: Reverses the order of elements along the vertical axis (axis 0), which means it mirrors the array along its horizontal axis.
Applicable to: 2D arrays (matrices).

Example:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Flip array vertically
flipped_ud = np.flipud(array_2d)

print("Original 2D array:\n", array_2d)
print("Vertically flipped array:\n", flipped_ud)

#Output:
Original 2D array:
 [[1 2 3]
  [4 5 6]
  [7 8 9]]
Vertically flipped array:
 [[7 8 9]
  [4 5 6]
  [1 2 3]]


Effects on Various Array Dimensions

1. 2D Arrays:
fliplr(): Reverses the order of columns, effectively flipping the array horizontally.
flipud(): Reverses the order of rows, effectively flipping the array vertically.

2. D Arrays:
fliplr(): Does not apply directly since it's specific to 2D arrays.
flipud(): Also does not apply directly to 1D arrays. For a 1D array, you can use slicing [::-1] to reverse it.

Example:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Reverse the 1D array
reversed_1d = array_1d[::-1]

print("Original 1D array:", array_1d)
print("Reversed 1D array:", reversed_1d)
# Output:
Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


3. Higher-dimensional Arrays:

fliplr(): Applies to the last two dimensions. For example, if you have a 3D array, it will flip the last two dimensions horizontally.
flipud(): Applies to the first two dimensions. For a 3D array, it will flip the first two dimensions vertically.

Example for 3D array:
import numpy as np

# Create a 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[7, 8, 9], [10, 11, 12]]])

# Flip horizontally (last two dimensions)
flipped_lr_3d = np.fliplr(array_3d)

# Flip vertically (first two dimensions)
flipped_ud_3d = np.flipud(array_3d)

print("Original 3D array:\n", array_3d)
print("Horizontally flipped 3D array:\n", flipped_lr_3d)
print("Vertically flipped 3D array:\n", flipped_ud_3d)
# Output:
Original 3D array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Horizontally flipped 3D array:
[[[ 3  2  1]
  [ 6  5  4]]

 [[ 9  8  7]
  [12 11 10]]]
Vertically flipped 3D array:
[[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]



In [ ]:
# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The array_split() method in NumPy is used to split an array into multiple sub-arrays. It offers flexibility in splitting arrays along a specified axis, and it can handle cases where the splits are uneven. Here’s a detailed discussion on its functionality and how it deals with uneven splits:

Functionality of array_split()
Syntax:
numpy.array_split(ary, indices_or_sections, axis=0)

1. ary: The input array to be split.
2. indices_or_sections: Specifies how to split the array:
- Integer: The number of equal-sized sub-arrays to return. If the array size is not perfectly divisible by this number, the last sub-array may be smaller.
- 1-D array of indices: Indicates where to split the array. This must be a 1-D array of sorted integers.
3. axis: The axis along which to split the array. Default is 0 (along rows for 2D arrays).



Handling Uneven Splits
When the size of the array is not evenly divisible by the number of sections, array_split() adjusts by making some sub-arrays smaller. Here’s how it handles uneven splits:

1. Integer for indices_or_sections: If you specify an integer N, NumPy will attempt to create N sub-arrays. If the array cannot be evenly divided, some of the resulting sub-arrays will contain fewer elements than others.

2. Array of Indices for indices_or_sections: If you provide an array of indices, NumPy will split the array at those indices. The resulting sub-arrays are determined by the specified indices, which can also lead to uneven sizes.


Examples: 


1. Splitting into Uneven Parts Using Integer:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split the array into 4 parts
split_array = np.array_split(array_1d, 4)

print("Original array:", array_1d)
print("Split arrays:")
for i, sub_array in enumerate(split_array):
    print(f"Sub-array {i}:", sub_array)
# Output:
Original array: [1 2 3 4 5 6 7 8 9]
Split arrays:
Sub-array 0: [1 2 3]
Sub-array 1: [4 5 6]
Sub-array 2: [7 8]
Sub-array 3: [9]


2. Splitting Using Indices:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split the array at indices 2 and 5
split_array = np.array_split(array_1d, [2, 5])

print("Original array:", array_1d)
print("Split arrays:")
for i, sub_array in enumerate(split_array):
    print(f"Sub-array {i}:", sub_array)
# Output:
Original array: [1 2 3 4 5 6 7 8 9]
Split arrays:
Sub-array 0: [1 2]
Sub-array 1: [3 4 5]
Sub-array 2: [6 7]
Sub-array 3: [8 9]


In [ ]:
# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Vectorization

Concept: Vectorization refers to the process of replacing explicit loops with array operations that are applied to entire arrays simultaneously. It leverages low-level optimizations and parallelism to perform operations efficiently.
Instead of iterating through elements of arrays using Python loops, NumPy operations are implemented in C or Fortran and are highly optimized for performance. This allows for element-wise operations to be executed more quickly.

Benefits:
- Performance: Vectorized operations are typically much faster than equivalent operations using explicit loops because they are implemented in lower-level languages and make use of efficient CPU instructions.
- Conciseness: Vectorized code is more concise and readable compared to code using explicit loops.

Example:
import numpy as np

# Create two large arrays
array1 = np.arange(1e6)
array2 = np.arange(1e6, 2e6)

# Vectorized addition
result = array1 + array2
In this example, adding array1 and array2 is done in a vectorized manner, resulting in fast and efficient computation.

Broadcasting

Concept: Broadcasting is a technique that allows NumPy to perform element-wise operations on arrays of different shapes and sizes. It automatically expands the smaller array to match the shape of the larger array during operations.
Broadcasting works by aligning the shapes of arrays in such a way that the operation can be applied element-wise. This is done by "stretching" the smaller array along dimensions where its size is 1.

Rules for Broadcasting:
1. Align Shapes: The shapes of the arrays must be compatible. If they do not match, NumPy will attempt to broadcast the smaller array to match the larger array's shape.
2. Size 1: Dimensions of size 1 in the smaller array can be stretched to match the corresponding dimensions of the larger array.
3. Matching: The sizes of the dimensions should either be equal or one of them should be 1.

Example:
import numpy as np

# Create a 2D array
array2d = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 1D array (scalar)
array1d = np.array([10, 20, 30])

# Broadcasting: add the 1D array to each row of the 2D array
result = array2d + array1d

print("Original 2D array:\n", array2d)
print("1D array:\n", array1d)
print("Broadcasted result:\n", result)
# Output:
Original 2D array:
 [[1 2 3]
  [4 5 6]]
1D array:
 [10 20 30]
Broadcasted result:
 [[11 22 33]
  [14 25 36]]
In this example, array1d is broadcasted to match the shape of array2d, allowing for element-wise addition.


Contributions to Efficient Array Operations

1. Speed:
Vectorization: Eliminates the need for explicit loops and leverages low-level optimizations, resulting in faster execution of operations.
Broadcasting: Enables efficient handling of operations between arrays of different shapes without the need for manual expansion or reshaping.

2. Memory Efficiency:
Vectorization: Operates directly on the array data without intermediate results being stored in Python objects, reducing memory overhead.
Broadcasting: Avoids unnecessary duplication of data by expanding dimensions virtually, thus saving memory.

3. Code Simplicity:
Vectorization: Reduces the complexity of code, making it more readable and maintainable.
Broadcasting: Allows for concise and intuitive operations on arrays of different shapes, simplifying code and avoiding complex manual adjustments.

In [ ]:
Practical questions

In [ ]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

# Step 1: Create a 3x3 array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Step 2: Interchange rows and columns (transpose the array)
transposed_array = np.transpose(array_3x3)

# Alternatively, you can use the .T attribute to transpose the array
# transposed_array = array_3x3.T

print("Original 3x3 array:\n", array_3x3)
print("Transposed 3x3 array:\n", transposed_array)

#output : 
Original 3x3 array:
 [[45 88 21]
  [16 92 75]
  [38 48 62]]
Transposed 3x3 array:
 [[45 16 38]
  [88 92 48]
  [21 75 62]]



In [ ]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

import numpy as np

# Step 1: Generate a 1D array with 10 elements
array_1d = np.arange(10)

# Step 2: Reshape the 1D array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Step 3: Reshape the 2x5 array into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

print("Original 1D array:\n", array_1d)
print("Reshaped 2x5 array:\n", array_2x5)
print("Reshaped 5x2 array:\n", array_5x2)

#output: 
Original 1D array:
 [0 1 2 3 4 5 6 7 8 9]
Reshaped 2x5 array:
 [[0 1 2 3 4]
  [5 6 7 8 9]]
Reshaped 5x2 array:
 [[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]


In [ ]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

# Step 1: Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Step 2: Add a border of zeros around the 4x4 array
# The pad_width parameter specifies the number of rows/columns of padding to add
padded_array = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 array:\n", array_4x4)
print("Padded 6x6 array:\n", padded_array)

#output : 
Original 4x4 array:
 [[0.58318623 0.04734667 0.59372462 0.68013416]
  [0.86697818 0.44515345 0.08182394 0.56343456]
  [0.55079152 0.73774342 0.8393124  0.12968421]
  [0.92594121 0.83563949 0.58514266 0.52095709]]
Padded 6x6 array:
 [[0. 0. 0. 0. 0. 0.]
  [0. 0.58318623 0.04734667 0.59372462 0.68013416 0.]
  [0. 0.86697818 0.44515345 0.08182394 0.56343456 0.]
  [0. 0.55079152 0.73774342 0.8393124  0.12968421 0.]
  [0. 0.92594121 0.83563949 0.58514266 0.52095709 0.]
  [0. 0. 0. 0. 0. 0.]]


In [ ]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

print("Array:", array)

#output: 
Array: [10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)

print("Original array:", string_array)
print("Uppercase array:", uppercase_array)
print("Lowercase array:", lowercase_array)
print("Titlecase array:", titlecase_array)

#output : 
Original array: ['python' 'numpy' 'pandas']
Uppercase array: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase array: ['python' 'numpy' 'pandas']
Titlecase array: ['Python' 'Numpy' 'Pandas']


In [ ]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

# Create a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy', 'array'])

# Function to insert space between characters of a word
def insert_spaces(word):
    return ' '.join(word)

# Apply the function to each element in the array
spaced_words_array = np.vectorize(insert_spaces)(words_array)

print("Original array:", words_array)
print("Array with spaces between characters:", spaced_words_array)


#output: 
Original array: ['hello' 'world' 'numpy' 'array']
Array with spaces between characters: ['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


In [ ]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10, 20, 30], [40, 50, 60]])

# Element-wise addition
addition_result = array1 + array2

# Element-wise subtraction
subtraction_result = array1 - array2

# Element-wise multiplication
multiplication_result = array1 * array2

# Element-wise division
division_result = array1 / array2

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Element-wise addition:\n", addition_result)
print("Element-wise subtraction:\n", subtraction_result)
print("Element-wise multiplication:\n", multiplication_result)
print("Element-wise division:\n", division_result)


#output: 
Array 1:
 [[1 2 3]
  [4 5 6]]
Array 2:
 [[10 20 30]
  [40 50 60]]
Element-wise addition:
 [[11 22 33]
  [44 55 66]]
Element-wise subtraction:
 [[ -9 -18 -27]
  [-36 -45 -54]]
Element-wise multiplication:
 [[ 10  40  90]
  [160 250 360]]
Element-wise division:
 [[0.1        0.1        0.1       ]
 [0.1        0.1        0.1       ]]


In [ ]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:\n", diagonal_elements)

#output: 
5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]
Diagonal Elements:
 [1. 1. 1. 1. 1.]


In [ ]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Step 2: Define a function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Step 3: Find and display all prime numbers in the array
primes = np.array([num for num in random_array if is_prime(num)])

print("Random Array:\n", random_array)
print("Prime Numbers:\n", primes)


#output: 
Random Array:
 [  94  682  892  251  953  643  329  903  461  485  523  127  973  196  877  329  509  795  579  920
  237  567  897  523  641  132  489  176  142  297  107  142  129  953  304  398  727  226  563  712  137
  231  398  243  251  290  263  338  929  287  295  733  957  542  287  477  307  353  821  779  649  268
  771  874  318  574  239  489  284  455  673  763  577  439  593  309  393  271  901  428  938  213  234]
Prime Numbers:
 [  251  953  643  523  127  877  509  461  107  137  131  113  211  223
  241  929  307  353  821  673  307  433]


In [ ]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

